export const LANG_RU_NAME = 'ru';

export const LANG_RU_TRANS = {
  'Search ASOS': 'Поиск на ASOS',
  'Welcome to ASOS': 'Добро пожаловать на ASOS!',
  'Join': ' Регистрация',
  'Sign In': 'Войти',
  'Help': 'Помошь',
  'My Account': 'Личный кабинет',
  'Saved Items': 'Избранное',
  'Bag': 'Корзина',
  'Questions?': 'Вопросы?',
  'Track Order': 'Отследить заказ',
  'Delivery': 'Доставка',
  'Returns': 'Возвраты',
  'What\'s in store' : 'В наличии',
  'Women': 'Женское',
  'Men': 'Мужское',
  'Buy Gift Vouchers': 'Купить подарочный сертификат',
  'Follow asos': 'Asos в социальных сетях',
  'More about asos': 'Подробнее об ASOS',
  'Corporate Responsibility': 'Корпоративная ответственность',
  'Jobs at ASOS': 'Вакансии в ASOS',
  'Investors': 'Инвесторам',
  'More asos sites': 'Другие сайты ASOS',
  'Mobile and ASOS apps': 'Мобильные приложение ASOS',
  'Marketplace': 'Торговая площадка',
  'Privacy & Cookies': 'Конфиденциальность и cookie-файлы',
  'Terms & Conditions': 'Правила и условия',
  'Accessibility': 'Доступность',
  'About Us': 'О нас',
  'The celebrities named or featured on asos.com have not endorsed recommended or approved the items offered on site': 'Упоминание ' +
'знаменитостей на asos.com не означает их одобрение или рекомендацию ' +
'относительно товаров, предлагаемых на сайте.',
  'Shop by product': 'Все категории',
  'New In: Clothing': 'Новинки: одежда',
  'New In: Shoes & Acc': 'Новинки: обувь и аксессуары',
  'Accessories': 'Аксессуары',
  'Sportswear': 'Cпортивная одежда',
  'Asos Basic Tops': 'Топы ASOS Basic',
  'Bags & Purses': 'Сумки и кошельки',
  'Beauty': 'Косметика',
  'Coats & Jackets': 'Пальто и куртки',
  'Curve & Plus Size': 'ASOS Curve',
  'Designer': 'Дизайнеры',
  'Dresses': 'Платья',
  'Gifts': 'Подарки',
  'Hoodies & Sweatshirts': 'Худи и свитшоты',
  'Jeans': 'Джинсы',
  'Shirts': 'V',
  'Polo Shirts': 'Футболки-поло',
  'Refine by': 'Сортировать по',
  'Collection': 'Коллекция',
  'Jerseys': 'Майки',
  'Jackets': 'Куртки',
  'Color': 'Цвет',
  'Black': 'Черный',
  'Red': 'Красный',
  'White': 'Белый',
  'Green': 'Зеленый',
  'Yellow': 'Желтый',
  'Multi': 'Мульти',
  'Size': 'Размер',
  'Brand': 'Бренд',
};
