export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'hello world': 'hello world',
  'Search': '',
  'Welcome to ASOS': '',
  'Join': '',
  'Sign In': '',
  'Help': '',
  'My Account': '',
  'Saved Items': '',
  'Bag': '',
  'Questions?': '',
  'Track Order': '',
  'Devively': '',
  'Returns': '',
  'What\'s in store' : '',
  'Women': '',
  'Men': '',
  'Buy Gift Vouchers': '',
  'Follow asos': '',
  'Facebook': '',
  'Twitter': '',
  'YouTube': '',
  'More about asos': '',
  'Corporate Responsibility': '',
  'Jobs at ASOS': '',
  'Investors': '',
  'More asos sites': '',
  'Mobile and ASOS apps': '',
  'Marketplace': '',
  'Privacy & Cookies': '',
  'Terms & Conditions': '',
  'Accessibility': '',
  'About Us': '',
  'The celebrities named or featured on asos.com have not endorsed recommended or approved the items offered on site': '',
  'Shop by product': '',
  'New In: Clothing': '',
  'New In: Shoes & Acc': '',
  'Accessories': '',
  'Sportswear': '',
  'Asos Basic Tops': '',
  'Bags & Purses': '',
  'Beauty': '',
  'Coats & Jackets': '',
  'Curve & Plus Size': '',
  'Dresses': '',
  'Gifts': '',
  'Hoodies-sweatshirts': '',
  'Jeans': '',
  'Shirts': '',
  'Polo-shirts': '',
};
